# 网站的基本信息
site:
  tab: Zayck # 浏览器标签栏上显示的文本
  title: Zayck # 网站的标题
  description: 系统 · 高效 · 实用 # 网站的描述，用于SEO等
  language: zh  # 网站的语言， "en" 是英文，"zh" 是中文
  favicon: /goat.png # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://shiki.style/themes
  date_format: YYYY-MM-DD # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  banner:
    height: "60vh"
  pages:
    home:  
      title: "Zayck' Blog"  
      subtitle: "系统 · 高效 · 实用"   
      typewriterTexts: # 新增打字机文本配置  
        - "系统 · 高效 · 实用"  
        - "软件 | 工具 | 效率 | 分享"  
        - "Diversity and Inclusiveness！"  
    friend:  
      title: "Friends"  
      subtitle: "欢迎互相访问交流，分享彼此的故事"  
    about:  
      title: "About Me"  
      subtitle: "一个热爱生活与技术的普通人！" 
    navigation:  
      title: "网站导航"  
      subtitle: "收藏的常用网站和工具链接"  
    project:
      title: "Projects"
      subtitle: "展示一些个人搭建的项目，搬运工！"
    sponsor:
      title: "赞助博主"
      subtitle: "☕一杯奶茶钱，鼓励博主继续深挖更多干货～"
    article:
      title: "Articles"
      subtitle: "个人思考、学习分享与生活记录"         
  menu: # 菜单配置
    - id: home
      text: 首页
      href: /
      svg: "feather:home"
      target: _self
    - id: sysj
      text: 少阳手记
      svg: "feather:book"
      target: _self
      subItems:
      - id: wanyi
        text: 玩易
        href: /blog/category/玩易
        svg: "feather:book-open"
        target: _self
      - id: xuanhuang
        text: 玄黄
        href: /blog/category/玄黄
        svg: "feather:book-open"
        target: _self
      - id: randeng
        text: 燃灯
        href: /blog/category/燃灯
        svg: "feather:book-open"
        target: _self
      - id: caotang
        text: 草堂
        href: /blog/category/草堂
        svg: "feather:book-open"
        target: _self
      - id: qingnang
        text: 青囊
        href: /blog/category/青囊
        svg: "feather:book-open"
        target: _self
      - id: niansi
        text: 廿四
        href: /html/廿四
        svg: "feather:book-open"
        target: _blank
      - id: yaoyan
        text: 妖言
        href: /blog/category/妖言
        svg: "feather:book-open"
        target: _self
      - id: zuowang
        text: 坐忘
        href: /blog/category/坐忘
        svg: "feather:book-open"
        target: _self

    - id: syyjs
      text: 少阳研究所
      svg: "feather:layers"
      target: _self
      subItems:
      - id: xlrj
        text: 效率软件
        href: /blog/category/效率软件
        svg: "feather:book-open"
        target: _self
      - id: sjwz
        text: 神级网站
        href: /blog/category/神级网站
        svg: "feather:book-open"
        target: _self
      - id: llqcj
        text: 浏览器插件
        href: /blog/category/浏览器插件
        svg: "feather:book-open"
        target: _self
      - id: hexo
        text: Hexo魔改
        href: /blog/category/Hexo魔改
        svg: "feather:book-open"
        target: _self
      - id: hugo
        text: Hugo魔改
        href: /blog/category/Hugo魔改
        svg: "feather:book-open"
        target: _self
      - id: Astro
        text: Astro魔改
        href: /blog/category/Astro魔改
        svg: "feather:book-open"
        target: _self
      - id: wzsz
        text: 网站实战
        href: /blog/category/网站实战
        svg: "feather:book-open"
        target: _self  
      - id: obsidian
        text: obsidian教程
        href: /blog/category/obsidian教程
        svg: "feather:book-open"
        target: _self
             
    - id: navigation  
      text: 导航  
      svg: "feather:compass"  
      target: _self
      subItems:
      - id: top
        text: 个人主页
        href: https://zayck-top.pages.dev
        svg: "feather:monitor"
        target: _blank
      - id: music
        text: 音乐网站
        href: /html/music
        svg: "feather:music"
        target: _blank  
      - id: tool
        text: 工具箱
        href: /navigation
        svg: "feather:tool"
        target: _self

    - id: about
      text: 关于
      svg: "feather:info"
      target: _self
      subItems:
      - id: more
        text: 关于我
        href: /about
        svg: "feather:smile"
        target: _self
      - id: project
        text: 项目
        href: /project
        svg: "feather:code"
        target: _self
      - id: friend
        text: 友链
        href: /friend
        svg: "feather:users"
        target: _self  
      - id: sponsor
        text: 赞助
        href: /sponsor
        svg: "feather:coffee"
        target: _self  

# 用户的个人信息
user:
  name: Zayck # 用户名
  site: "https://zayck.pages.dev" # 用户的网站链接
  avatar: /avatar.webp # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/zayck"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/341981702"
        ariaLabel: BiliBili
        title: Bilibili
        svg: "ri:bilibili-line"
      - href: "https://mp.weixin.qq.com/mp/homepage?__biz=MzU2MTI5MzE4OA==&hid=1&sn=356f3016aeac48fc034804fca1307349&scene=18#wechat_redirect"
        ariaLabel: wechat
        title: Wechat
        svg: "ri:wechat-2-line"
      - href: "/rss.xml"  
        ariaLabel: Subscribe via Folo  
        title: Rss
        svg: "feather:rss"

  footer:
    social:
      - href: "/sponsor"
        ariaLabel: 支持博主
        title: 支持博主
        svg: "feather:coffee"
      - href: "https://github.com/zayck"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/341981702"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://mp.weixin.qq.com/mp/homepage?__biz=MzU2MTI5MzE4OA==&hid=1&sn=356f3016aeac48fc034804fca1307349&scene=18#wechat_redirect"
        ariaLabel: wechat
        title: wechat
        svg: "ri:wechat-2-line"

# 评论系统配置
comments:
  enable: true # 是否启用评论
  type: waline # giscus/waline/none
  giscus:
    repo: "kobaridev/gsc"
    repoId: "R_kgDOPTM-mA"
    category: "General"
    categoryId: "DIC_kwDOPTM-mM4CtcFq"
    mapping: "pathname"
    lang: "zh-CN"
    inputPosition: "top"
    reactionsEnabled: "1"
    emitMetadata: "0"
    loading: "lazy"
  waline:
    serverURL: "https://waline.zayck34.dpdns.org"
    lang: "zh-CN"
    emoji:
      - "https://unpkg.com/@waline/emojis@1.1.0/weibo"
      - "https://unpkg.com/@waline/emojis@1.1.0/bilibili"
    meta: ["nick", "mail", "link"]
    requiredMeta: ["nick"]
    reaction: false
    pageview: false
# Umami 统计配置
umami:
  enable: false # 是否启用 Umami 统计
  baseUrl: "https://cloud.umami.is"
  shareId: "d438VyP7mjcHvTyP"
  websiteId: "3c570f5b-118c-4a22-9231-8a93bf15c200"
  timezone: "Asia/Shanghai"